version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin321!
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
