spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge
    password: admin321!
    username: admin
    driver-class: org.postgresql.Driver
logging:
  level:
    pl.levant.challenge: DEBUG
    org.zalando.logbook: TRACE
domain:
  forecast:
    feeding-rate: 60000
    feeding-delay: 0
  seven-timer:
    client:
      base-url: http://www.7timer.info/bin/api.pl
